changelog_path = "CHANGELOG.md"
pre_bump_hooks = [
    "cargo build --release",
    "cargo bump %version",
    "cargo check --release",
    "git add Cargo.lock",
]
post_bump_hooks = [
    "git push",
    "git push origin %version",
]
authors = [
    { signature = "Marcin Puc", username = "tranzystorek-io" },
]

[commit_types]
