changelog_path = "CHANGELOG.md"
pre_bump_hooks = [
    "cargo build --release",
    "cargo bump %version",
]
post_bump_hooks = [
    "git push",
    "git push origin %version",
]
authors = []

[commit_types]
